name: Discord Chat Sync

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install DiscordChatExporter
      run: |
        dotnet tool install -g DiscordChatExporter.Cli
        echo "/home/runner/.dotnet/tools" >> $GITHUB_PATH

    - name: Export Chat
      run: |
        discord-chat-exporter-cli export \
          -t "${{ secrets.DISCORD_TOKEN }}" \
          -c ${{ secrets.CHANNEL_ID }} \
          -f Json \
          -o chat_logs.json

    - name: Save file to GitHub
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add chat_logs.json
        git commit -m "Automated chat update" || exit 0
        git push
